### ISSUE TITLE
Class Neurone

### ISSUE THREAD

**Issue by simonberard** [EPFL-SV-cpp-projects/neuro-3#7]
Create a class neurone and it's attributes

**Comment by baleydier** [comment]
I commited it. (How should I push it?)

**Comment by simonberard** [comment]
I'm not sure if I understood your question but have you tried "git push" command?

**Comment by simonberard** [comment]
Could you just redefine the "update"function as a virtual method? It will allow us to define an update method into the subclasses

**Comment by baleydier** [comment]
Yes sure, the changes have just been done. You are right for the virtuality of the "update" method. :)
